#!/usr/bin/env bash
# Entrypoint of the all-in-one image (Dockerfile.aio): runs PostgreSQL and
# the ragmux gateway in one container.
#
#   ragmux-aio [gateway args...]   start Postgres, then the gateway (default)
#   ragmux-aio postgres-only       start only Postgres (backup/restore one-offs)
#
# Process model: this script is PID 1. It prepares /data as root, starts
# postgres as the postgres user, waits until it accepts connections on the
# unix socket, creates the ragmux database and the ragmux_app role (idempotent
# SQL shared with the split layout), then starts the gateway as the ragmux
# user. SIGTERM/SIGINT stop the gateway first, then Postgres (pg_ctl -m fast);
# if either process dies on its own the other one is stopped and the script
# exits non-zero so the container restarts.
#
# Embedded Postgres is skipped when the operator sets DATABASE_URL (or
# DATABASE_URL_FILE) or EMBEDDED_POSTGRES=false; the container then runs the
# gateway alone, like the app-only image.
set -euo pipefail

PGDATA="${PGDATA:-/data/pg}"
DATA_DIR="${DATA_DIR:-/data/ragmux}"
PG_SOCKET_DIR="${PG_SOCKET_DIR:-/var/run/postgresql}"
PG_SHARED_BUFFERS="${PG_SHARED_BUFFERS:-128MB}"
PG_DB="${PG_DB:-ragmux}"
PG_APP_ROLE="ragmux_app"
INIT_SQL="${RAGMUX_INIT_SQL:-/usr/local/share/ragmux/init.sql}"
PG_BIN="/usr/lib/postgresql/17/bin"

log() { printf 'ragmux-aio: %s\n' "$*" >&2; }
die() { log "error: $*"; exit 1; }

mode="gateway"
if [ "${1:-}" = "postgres-only" ]; then
  mode="postgres-only"
  shift
fi

# Embedded Postgres: on unless the operator brought their own database.
embedded="${EMBEDDED_POSTGRES:-}"
case "$embedded" in
  true|1|yes) embedded=true ;;
  false|0|no) embedded=false ;;
  '')
    if [ -n "${DATABASE_URL:-}" ] || [ -n "${DATABASE_URL_FILE:-}" ]; then
      embedded=false
    else
      embedded=true
    fi ;;
  *) die "EMBEDDED_POSTGRES must be true or false, got '$embedded'" ;;
esac
if [ "$mode" = "postgres-only" ] && [ "$embedded" != true ]; then
  die "postgres-only needs the embedded Postgres (unset DATABASE_URL / EMBEDDED_POSTGRES)"
fi

# ---- gateway only ----------------------------------------------------------
if [ "$embedded" != true ]; then
  if [ "$(id -u)" -eq 0 ]; then
    mkdir -p "$DATA_DIR"
    chown ragmux:ragmux "$DATA_DIR"
    chmod 700 "$DATA_DIR"
  fi
  log "embedded Postgres disabled; starting the gateway against DATABASE_URL"
  export DATA_DIR
  if [ "$(id -u)" -eq 0 ]; then
    exec gosu ragmux /usr/local/bin/ragmux "$@"
  fi
  exec /usr/local/bin/ragmux "$@"
fi

# ---- prepare /data ---------------------------------------------------------
[ "$(id -u)" -eq 0 ] || die "the embedded Postgres needs the container to start as root (it drops privileges itself)"
mkdir -p "$PGDATA" "$DATA_DIR" "$PG_SOCKET_DIR"
chown postgres:postgres "$PGDATA" "$PG_SOCKET_DIR"
chmod 700 "$PGDATA"
chown ragmux:ragmux "$DATA_DIR"
chmod 700 "$DATA_DIR"

# DB_MAX_CONNS is the gateway's pool size; leave headroom for the healthcheck
# pool, backups, psql sessions and PostgreSQL's own reserved slots.
db_max_conns="${DB_MAX_CONNS:-10}"
case "$db_max_conns" in ''|*[!0-9]*) db_max_conns=10 ;; esac
max_connections=$((db_max_conns + 10))
[ "$max_connections" -ge 100 ] || max_connections=100

first_init=false
if [ ! -s "$PGDATA/PG_VERSION" ]; then
  first_init=true
  log "initialising PostgreSQL cluster in $PGDATA"
  gosu postgres "$PG_BIN/initdb" -D "$PGDATA" --username=postgres \
    --encoding=UTF8 --locale=C.UTF-8 --auth-local=trust --auth-host=reject \
    >/dev/null
  # The overrides live in their own file so a running cluster keeps the
  # generated postgresql.conf untouched; the include is added once.
  printf "\n# ragmux all-in-one overrides (regenerated on every start)\ninclude = 'ragmux.conf'\n" \
    >>"$PGDATA/postgresql.conf"
elif [ "$(cat "$PGDATA/PG_VERSION")" != "17" ]; then
  die "$PGDATA holds a PostgreSQL $(cat "$PGDATA/PG_VERSION") cluster; this image ships 17 (dump and restore to move, see docs/backup-restore.md)"
fi

# Regenerated on every start so PG_SHARED_BUFFERS / DB_MAX_CONNS changes apply.
# No TCP listener at all: the gateway, backups and psql use the unix socket.
gosu postgres tee "$PGDATA/ragmux.conf" >/dev/null <<CONF
listen_addresses = ''
unix_socket_directories = '$PG_SOCKET_DIR'
shared_buffers = '$PG_SHARED_BUFFERS'
max_connections = $max_connections
log_line_prefix = 'postgres: %m [%p] '
log_timezone = 'UTC'
timezone = 'UTC'
CONF
# Trust on the local socket only: nothing else runs in this container, and the
# socket directory is not shared unless the operator mounts it (backup profile).
gosu postgres tee "$PGDATA/pg_hba.conf" >/dev/null <<HBA
# generated by ragmux-aio; TCP is never opened (listen_addresses = '')
local   all   all   trust
host    all   all   all   reject
HBA

# ---- start postgres --------------------------------------------------------
pg_pid=""
app_pid=""
stopping=false

stop_postgres() {
  if [ -n "$pg_pid" ] && kill -0 "$pg_pid" 2>/dev/null; then
    log "stopping postgres"
    gosu postgres "$PG_BIN/pg_ctl" -D "$PGDATA" stop -m fast -w -t 60 >/dev/null 2>&1 || kill -TERM "$pg_pid" 2>/dev/null || true
    wait "$pg_pid" 2>/dev/null || true
  fi
}
stop_gateway() {
  if [ -n "$app_pid" ] && kill -0 "$app_pid" 2>/dev/null; then
    log "stopping gateway"
    kill -TERM "$app_pid" 2>/dev/null || true
    wait "$app_pid" 2>/dev/null || true
  fi
}
on_signal() {
  stopping=true
  log "signal received, shutting down"
  stop_gateway
  stop_postgres
  exit 0
}
trap on_signal TERM INT

gosu postgres "$PG_BIN/postgres" -D "$PGDATA" &
pg_pid=$!

log "waiting for postgres on $PG_SOCKET_DIR"
deadline=$((SECONDS + 60))
until gosu postgres pg_isready -q -h "$PG_SOCKET_DIR" -U postgres; do
  kill -0 "$pg_pid" 2>/dev/null || die "postgres exited during startup"
  [ "$SECONDS" -lt "$deadline" ] || { stop_postgres; die "postgres did not accept connections within 60s"; }
  sleep 0.5
done

psql_super() { gosu postgres psql -v ON_ERROR_STOP=1 -qAt -h "$PG_SOCKET_DIR" -U postgres "$@"; }
if [ "$(psql_super -d postgres -c "SELECT 1 FROM pg_database WHERE datname = '$PG_DB'")" != "1" ]; then
  log "creating database $PG_DB"
  psql_super -d postgres -c "CREATE DATABASE \"$PG_DB\""
fi
# Idempotent: extension, role, grants and the ownership hand-over of existing
# tables (matters after a pg_restore run as postgres).
psql_super -d "$PG_DB" -v db="$PG_DB" -f "$INIT_SQL" >/dev/null
[ "$first_init" = true ] && log "database $PG_DB and role $PG_APP_ROLE created"
log "postgres ready (pid $pg_pid)"

# ---- start gateway ---------------------------------------------------------
if [ "$mode" = "gateway" ]; then
  export DATABASE_URL="postgres://${PG_APP_ROLE}@/${PG_DB}?host=${PG_SOCKET_DIR}&sslmode=disable"
  export DATA_DIR
  gosu ragmux /usr/local/bin/ragmux "$@" &
  app_pid=$!
  log "gateway started (pid $app_pid)"
else
  log "postgres-only mode: no gateway"
fi

# ---- supervise -------------------------------------------------------------
# wait -n returns when any child exits; a trapped signal interrupts it and the
# handler above exits the script itself.
while true; do
  code=0
  wait -n || code=$?
  [ "$stopping" = true ] && exit 0
  if [ -n "$app_pid" ] && ! kill -0 "$app_pid" 2>/dev/null; then
    if [ "$code" -eq 0 ]; then
      log "gateway exited"
    else
      log "gateway exited with status $code"
    fi
    stop_postgres
    exit "$code"
  fi
  if ! kill -0 "$pg_pid" 2>/dev/null; then
    log "postgres exited with status $code"
    stop_gateway
    [ "$code" -ne 0 ] && exit "$code"
    exit 1
  fi
done
